src/Entity/Appointment.php
<?php

namespace App\Entity;

use App\Repository\AppointmentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Nullable;

#[ORM\Entity(repositoryClass: AppointmentRepository::class)]
class Appointment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_of_appointment = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $start_hour = null;

    #[ORM\ManyToOne(inversedBy: 'appointments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Patient $patient = null;

    #[ORM\ManyToOne(inversedBy: 'appointments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Doctor $doctor = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateOfAppointment(): ?\DateTimeInterface
    {
        return $this->date_of_appointment;
    }

    public function setDateOfAppointment(\DateTimeInterface $date_of_appointment): static
    {
        $this->date_of_appointment = $date_of_appointment;

        return $this;
    }

    public function getStartHour(): ?\DateTimeInterface
    {
        return $this->start_hour;
    }

    public function setStartHour(\DateTimeInterface $start_hour): static
    {
        $this->start_hour = $start_hour;

        return $this;
    }


    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getDoctor(): ?Doctor
    {
        return $this->doctor;
    }

    public function setDoctor(?Doctor $doctor): static
    {
        $this->doctor = $doctor;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Patient.php
<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PatientRepository::class)]
class Patient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 15)]
    #[Assert\Length(min: 15, max: 15, minMessage: "Ce champ doit contenir exactement 15 caractères")]
    #[Assert\Regex('/^[0-9]+$/',message: 'Ce champ ne peut contenir que des chiffres')]
    private ?string $social_security_number = null;

    #[ORM\OneToOne(inversedBy: 'patient', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(targetEntity: Appointment::class, mappedBy: 'patient')]
    private Collection $appointments;

    public function __construct()
    {
        $this->appointments = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSocialSecurityNumber(): ?string
    {
        return $this->social_security_number;
    }

    public function setSocialSecurityNumber(string $social_security_number): static
    {
        $this->social_security_number = $social_security_number;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Appointment>
     */
    public function getAppointments(): Collection
    {
        return $this->appointments;
    }

    public function addAppointment(Appointment $appointment): static
    {
        if (!$this->appointments->contains($appointment)) {
            $this->appointments->add($appointment);
            $appointment->setPatient($this);
        }

        return $this;
    }

    public function removeAppointment(Appointment $appointment): static
    {
        if ($this->appointments->removeElement($appointment)) {
            // set the owning side to null (unless already changed)
            if ($appointment->getPatient() === $this) {
                $appointment->setPatient(null);
            }
        }

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Form\PatientType;
use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $email = null;

    #[ORM\Column(length: 10)]
    #[Assert\Regex('/^[0-9]+$/',message: "Ce champ ne peut contenir que des chiffres")]
    private ?string $phone = null;

    #[ORM\Column(length: 30)]
    private array $roles = [];

    #[ORM\Column(length: 64)]
    /*
    * Regex pour les conditions que j'ai imposées pour le mot de passe:
    * mini 1 Maj, 1 mini, 1 chiffre, 1 caractère spécial
    * mini 12 caractères
    *
    * */
    #[Assert\Regex(
        '/^(?=.*[!@#$%^&*-_])(?=.*[0-9])(?=.*[A-Z]).{12,}$/',
        message: "Le mot de passe doit être composé d'au moins 12 caractères et contenir au moins: 1 minuscule, 1 majuscule, 1 chiffre et un caractère spécial")]

    private ?string $password = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;


    #[ORM\Column(length: 80)]
    #[Assert\Length(min: 2,minMessage: 'Ce champ doit contenir au moins 2 caractères')]
    #[Assert\Regex(
        '/^[a-zA-Zéè\'-]+$/',
        message: "Le prénom ne peut contenir que des lettres et les caractères \" ' ou -\" ")]
    protected ?string $first_name = null;

    #[ORM\Column(length: 50)]
    #[Assert\Length(min: 2,minMessage: 'Ce champ doit contenir au moins 2 caractères')]
    #[Assert\Regex(
        '/^[a-zA-Z\'-]+$/',
        message: "Le nom de famille ne peut contenir que des lettres et les caractères \" ' ou -\" ")]
    protected ?string $last_name = null;

    #[ORM\ManyToOne(targetEntity: Civility::class,inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Type(type: Civility::class)]
    #[Assert\Valid]
    protected?Civility $civility = null;

    #[ORM\ManyToOne(targetEntity:Address::class,inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Type(type: Address::class)]
    #[Assert\Valid]
    protected ?Address $address = null;

    #[ORM\OneToOne(targetEntity: Patient::class, mappedBy: 'user', cascade: ['persist', 'remove'])]
    #[Assert\Type(type: Patient::class)]
    #[Assert\Valid]
    protected ?Patient $patient = null;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    protected ?Doctor $doctor = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_Of_Birth = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $fullName = null;

    public function getFullName(): string
    {
        return $this->first_name.' '.$this->last_name;
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCivility(): ?Civility
    {
        return $this->civility;
    }

    public function setCivility(?Civility $civility): static
    {
        $this->civility = $civility;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(Patient $patient): static
    {
        // set the owning side of the relation if necessary
        if ($patient->getUser() !== $this) {
            $patient->setUser($this);
        }

        $this->patient = $patient;

        return $this;
    }

    public function getDoctor(): ?Doctor
    {
        return $this->doctor;
    }

    public function setDoctor(Doctor $doctor): static
    {
        // set the owning side of the relation if necessary
        if ($doctor->getUser() !== $this) {
            $doctor->setUser($this);
        }

        $this->doctor = $doctor;

        return $this;
    }
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    #[ORM\PrePersist]
    public function setCreateAtValue(): void
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_Of_Birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_Of_Birth): static
    {
        $this->date_Of_Birth = $date_Of_Birth;

        return $this;
    }

    public function setFullName(?string $fullName): static
    {
        $this->fullName = $fullName;

        return $this;
    }




}

src/Form/PatientType.php
<?php

namespace App\Form;

use App\Entity\Patient;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Contracts\Translation\TranslatorInterface;

class PatientType extends AbstractType
{
    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator=$translator;

    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('social_security_number', TextType::class, [
                'label'=> 'N° de sécurité social',
                'constraints' => [
                    new Length(min: 15, max: 15, exactMessage:'Ce champ doit contenir 15 caractères'),
                    new Regex('/^[0-9]+$/',message: 'Ce champ ne peut contenir que des chiffres')]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Patient::class,
        ]);
    }
}

src/Controller/PatientController.php
<?php

namespace App\Controller;

use App\Entity\Appointment;
use App\Entity\User;
use App\Form\UserPasswordType;
use App\Form\UserType;
use App\Repository\AppointmentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Component\Clock\now;

class PatientController extends AbstractController
{
    #[Route('/Patient/mon_compte.html',name:'app_patient_patienthome')]
    public function patientHome():Response
    {
        return $this->render('patient/patienthome.html.twig');

    }

    #[Route('/Patient/mon_compte/modification.html',name: 'app_patient_patientUpdate')]
    public function editPatient(Request $request, EntityManagerInterface $em):Response
    {

        $user = $this->getUser();

        $form = $this->createForm(UserType::class, $user);
        $form->remove('password');
        $form->remove('Doctor');

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()){


            /** @var User $user */
            $user=$form->getData();

            $last_name=$user->getLastName();
            $last_name=strtoupper(strip_tags($last_name));
            $user->setLastName($last_name);

            $first_name=$user->getFirstName();
            $first_name=ucwords(strip_tags($first_name),"\ \-");
            $user->setFirstName($first_name);

            $user->setFullName($first_name.' '.$last_name);

            $user->setUpdatedAt(new \DateTimeImmutable());

            $em->persist($user);
            $em->flush();

            $this->addFlash('success','Votre profil a bien été mis à jour');

            return $this->redirectToRoute('app_patient_patienthome');

        }

        return $this->render('patient/patientModification.html.twig',[
            'form'=>$form
    ]);
    }

    #[Route('/Patient/myAppointment.html', name: 'app_patient_myAppointments')]
        public function appointmentManagementPatient(AppointmentRepository $appointmentRepository):Response
    {

        $user=$this->getUser();
        /** @var  User $user */
        $id=$user->getPatient()->getId();
        $myAppointments = $appointmentRepository->findBy(['patient'=>$id]);

        return $this->render('patient/myAppointments.html.twig',[
            'appointments'=>$myAppointments
        ]);

    }

    #[Route('/Patient/myAppointment/{id}/annule.html', name: 'app_patient_annulappointment')]
    public function annulAppointment(Appointment $appointment, EntityManagerInterface $entityManager): RedirectResponse
    {
        $appointment->setStatus('Annule');
        $entityManager->persist($appointment);
        $entityManager->flush();
        $this->addFlash('success','votre rendez vous a bien été annulé');
        return $this->redirectToRoute('');
    }

}

templates/patient/myAppointments.html.twig
{% extends "base.html.twig" %}
{% block title %}Mes rendez-vous{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="container-fluid bg-primary">
        <div style="height: 200px" class="row d-flex-column justify-content-center align-items-center dodo">
            <div style="width: 200px; height: 200px" class="d-flex justify-content-center align-items-center px-0 mt-1 me-1">
                <img  class="rounded-circle w-75 h-75 object-fit-cover" src="{{ asset('assets/images/defaut-avatar-profil.jpg') }}" alt="Avatar du profil">
            </div>

        </div>
    </div>
    <div class="container py-3">
        <div class="border rounded shadow">
            <h3 class="text-center">{{ app.user.fullName }}</h3>

        </div>

        <div class="d-block align-items-center border rounded shadow mt-3">
            <h4 class="text-center text-decoration-underline">Demande de rendez-vous en cours</h4>
            {% if appointments is not empty %}

                {% for i in appointments %}
                    {% if i.status == "En attente" %}

                        <div class="d-flex justify-content-center align-items-center">
                            <p class="me-5">{% if i.patient.user.civility.sexe is same as true %}Mr. {% else %}Mme. {% endif %}{{ i.patient.user.fullName }}, le {{ i.dateOfAppointment|date('d/m/y')}} à {{ i.startHour|date('h:i') }}</p>
                            
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p>Il n'y aucun rendez-vous en attente de validation</p>
            {% endif %}
        </div>
        <div class="row d-flex border rounded shadow mt-3 mx-auto" >
            <div class="col-6 border-end border-primary-subtle">
                <h4 class="text-center text-decoration-underline">Rendez-vous à venir</h4>
                <p class="fst-italic text-center">Civilité Nom Prénom (Jour rdv, heure rdv)</p>
                {% if appointments is not empty %}
                    <ul>
                        {% for i in appointments %}
                            {% if i.status == "Accepted" and i.dateOfAppointment > date('now') %}
                                <div class="d-flex justify-content-center align-items-center">
                                    <p class="me-5">{% if i.patient.user.civility.sexe is same as true %}Mr. {% else %}Mme. {% endif %}{{ i.patient.user.fullName }}, le {{ i.dateOfAppointment|date('d/m/y')}} à {{ i.startHour|date('h:i') }}</p>
                                    <div>
                                        {#  <button class="btn btn-success me-2">Accepter</button>
                        <button class="btn btn-danger">Refuser</button>#}
                                    </div>
                                </div>
                            {% endif %}

                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Il n'y aucun rendez-vous en attente de validation</p>
                {% endif %}
            </div>
            <div class="col-6">
                <h4 class="text-center text-decoration-underline">Rendez-vous passés</h4>
                <p class="fst-italic text-center">Civilité Nom Prénom (Jour rdv, heure rdv)</p>
            </div>
        </div>
    </div>





{% endblock %}

templates/patient/patientModification.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mise à jour du profil{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div style="height: 150px" class="row d-flex justify-content-end bg-primary">
            <div style="width: 80px; height: 80px" class="px-0 mt-1 me-1">
                <img  class="img-fluid rounded-circle" src="{{ asset('assets/images/defaut-avatar-profil.jpg') }}" alt="Avatar du profil">
            </div>
            <div class="d-flex justify-content-center align-items-center">
                {% if  app.user %}
                    <p class="text-white text-center h1">{{ app.user.fullName }}</p>
                {% endif %}


            </div>
        </div>
    </div>
    <div class="container py-3">
    <h3 class="text-center">Modifiez vos informations personnelles</h3>
    <div class="col-6 mx-auto border rounded shadow p-3 my-3 ">
        <form class="infosPatient" action="" method="post">
            {{ form_start(form) }}
            {#
            <label class="mb-2 mt-1" for="inputCivility">Civilité</label>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    {% if app.user.civility.sexe %}Mr.{% else %}Mme.{% endif%}
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li class="dropdown-item">Mr.</li>
                    <li class="dropdown-item">Mme.</li>
                </ul>
            </div>
            #}
            <div class="Form-group patmodi">
                {{ form_row(form.Civility.sexe) }}
            </div>
            <div class="Form-group patmodi">
                {{ form_row(form.last_name) }}
            </div>
            <div class="Form-group patmodi">
                {{ form_row(form.first_name) }}
            </div>
            <div class="Form-group patmodi">
                {{ form_row(form.date_Of_Birth) }}
            </div>
            <div class="Form-group patmodi">
                {{ form_row(form.Patient) }}
            </div>
            <div class="Form-group patmodi">
                {{ form_row(form.Address.street_name) }}
            </div>
            <div class="Form-group patmodi">
                {{ form_row(form.Address.city_name) }}
            </div>
            <div class="Form-group patmodi">
                {{ form_row(form.Address.postal_code) }}
            </div>
            <div class="Form-group patmodi">
                {{ form_row(form.email) }}
            </div>
            <div class="Form-group patmodi">
                {{ form_row(form.phone) }}
            </div>
            <div class="Form-group ">
                {{ form_row(form.submit, {'attr':{'class': 'btn btn-success justify-content-center w-50'}}) }}
            </div>
            {{ form_end(form) }}

        </form>
        {# <div class="d-flex justify-content-center mt-3">
            <button class="btn btn-success w-50">Valider</button>
        </div> #}
    </div>

{% endblock %}

templates/patient/patienthome.html.twig
{% extends "base.html.twig" %}
{% block title %}Mon profil{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="container-fluid">
        <div style="height: 150px; background-color: #059BE6" class="row d-flex-column justify-content-end">
            <div style="width: 80px; height: 80px" class="px-0 mt-1 me-1">
                <img  class="img-fluid rounded-circle" src="{{ asset('assets/images/defaut-avatar-profil.jpg') }}" alt="Avatar du profil">
            </div>
            <div class="d-flex justify-content-end align-items-end">
                {% if  app.user %}
                    <p class="text-white">Bonjour, {{ app.user.fullName }}</p>
                {% endif %}


            </div>
        </div>
    </div>
    <div class="container py-3">
        <h3 class="text-center">Informations personnelles</h3>
        <div class="col-6 mx-auto border rounded shadow p-3 my-3 ">
            <form class="infosForm" action="">
                <label class="mb-2 mt-1" for="inputCivility">Civilité</label>
                <input type="text" readonly value= "{% if app.user.civility.sexe %}Mr.{% else %}Mme.{% endif%}" name="civility" id="inputCivility" class="form-control">
                <label class="mb-2 mt-1" for="inputLast_name">Nom</label>
                <input type="text" readonly value= "{{ app.user.lastName }}" name="last_name" id="inputLast_name" class="form-control">
                <label class="mb-2 mt-1" for="inputFirst_name">Prénom</label>
                <input type="text" readonly value= "{{ app.user.firstName }}" name="fist_name" id="inputFirst_name" class="form-control">
                <label class="mb-2 mt-1" for="inputDOB">Date de naissance</label>
                <input type="text" readonly value= "{{ app.user.dateOfBirth|date('d/m/Y') }}" name="date_of_birth" id="inputDOB" class="form-control">
                <label class="mb-2 mt-1" for="inputSecuSociale">N° Sécurité Sociale</label>
                <input type="text" readonly value= "{{ app.user.patient.socialSecurityNumber }}" name="SecuSociale" id="inputSecuSociale" class="form-control">
                <label class="mb-2 mt-1" for="inputAddress">Adresse</label>
                <input type="text" readonly value= "{{ app.user.address }}" name="address" id="inputAddress" class="form-control">
                <label class="mb-2 mt-1" for="inputEmail">Email</label>
                <input type="text" readonly value= "{{ app.user.email }}" name="email" id="inputEmail" class="form-control">
                <label class="mb-2 mt-1" for="inputPhone">Téléphone</label>
                <input type="text" readonly value= "{{ app.user.phone }}" name="phone" id="inputPhone" class="form-control">

            </form>
            <div class="d-flex justify-content-center mt-3">
                <a class="w-50" href="{{ path('app_patient_patientUpdate') }}"><button class="btn vali w-100">Modifier</button></a>
            </div>
        </div>
    <h3 class="text-center">Mot de passe</h3>
    <div class="col-6 mx-auto border rounded shadow p-3 my-3 ">
        <form class="infosForm" action="">
            <input type="text" readonly value= "xxxxxxxxxxxxxxx" name="civility" id="inputCivility" class="form-control text-center">
        </form>
        <div class="d-flex justify-content-center mt-3">
            <a class="w-50" href="{{ path('app_editpassword',{'id':app.user.id}) }}"><button class="btn vali w-100">Modifier</button></a>
        </div>
    </div>
{% endblock %}